# Generated by Django 2.1.1 on 2018-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180912_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='roleid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='roleid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userid',
        ),
        migrations.AddField(
            model_name='users',
            name='rolename',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
