# Generated by Django 2.1.1 on 2018-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180913_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rolename',
            field=models.CharField(max_length=20),
        ),
    ]
