# Generated by Django 2.1.1 on 2018-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180913_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rolename',
        ),
        migrations.AddField(
            model_name='users',
            name='rolename',
            field=models.ManyToManyField(to='api.Roles'),
        ),
    ]
