# Generated by Django 2.1.1 on 2018-09-13 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180913_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rolename',
        ),
        migrations.AddField(
            model_name='users',
            name='rolename',
            field=models.CharField(default=' ', max_length=20, verbose_name=api.models.Roles),
        ),
    ]
