# Generated by Django 2.1.1 on 2018-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180913_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='rolename',
            new_name='roles',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rolename',
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
