# Generated by Django 2.1.1 on 2018-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180913_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='roles',
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(to='api.Roles'),
        ),
    ]
