# Generated by Django 2.1.1 on 2018-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180913_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='id',
        ),
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(to='api.Roles'),
        ),
    ]
