# Generated by Django 2.1.1 on 2018-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180914_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(to='api.Roles'),
        ),
    ]
